config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users
  resources :links

  get 'links/:id/vote' => "links#vote", as: :vote

end

app/models/link.rb
class Link < ActiveRecord::Base

  belongs_to :user

  # validates :title, presence: true
  # validates :url, presence: true
  validates :url, :format => URI::regexp(%w(http https))
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :links

  def link_urls
    links.map{ |link| link.url }.join(" == ")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    @link = Link.new
  end

  def create
    @link = Link.new params.require(:link).permit(:url, :user_id, :title)
    if @link.save
      redirect_to root_path
    else
      render :new
    end
  end

  def vote
    @link = Link.find params[:id]
    @link.vote += 1
    @link.save
    redirect_to @link.url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @links = Link.all.order("vote desc")
  end

  def show
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new params.require(:link).permit(:url, :user)
    if @link.save
      redirect_to user_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fakereddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<div class="container">

  <h1 class="page-header"> Welcome to fReddit!<small> -the new black hole</small> </h1>

  <div>
    <%= link_to "Add a New Link", new_user_path %>
  </div>
  <br>
  <ul>
    <% @links.each do |link| %>
      <li>
        <div class="alert alert-info" role="alert">
        <h4> <%= link.title.upcase %> </h4>
        <!-- <%= link_to(link.url, link.url) %> -->
        <%= link_to link.url, vote_path(link) %>
        <br>
        <p>
          Posted by: <%= link.user.name %>
          --- <%= pluralize link.vote, 'views' %>
        </p>
      </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/links/new.html.erb
<div class="container">
  Post a new link


  <%= form_for @link do |f| %>

  <div>
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </div>

    <div>
      <%= f.label :url %>
      <br/>
      <%= f.url_field :url %>
    </div>

    <div>
      <%= f.label :user %>
      <br/>
      <%= f.select(:user_id, User.all.map {|p| [p.name, p.id]}) %>
    </div>

    <div>
      <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  Post a new link


  <%= form_for @link do |f| %>

  <div>
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </div>

    <div>
      <%= f.label :url %>
      <br/>
      <%= f.text_field :url %>
    </div>

    <div>
      <%= f.label :user %>
      <br/>
      <%= f.select(:user_id, User.all.map {|p| [p.name, p.id]}) %>
    </div>

    <div>
      <%= f.submit %>
    </div>

  <% end %>
</div>